project:
  type: book
  output-dir: docs

book:
  title: "Probability & Statistics"
  author: "Jim Brooke"
  date: "16/09/2024"
  chapters:
    - index.qmd
    - measurement.qmd
    - histograms.qmd
    - singlestats.qmd
    - multistats.qmd
    - probability.qmd
    - distributions.qmd
    - theorydist.qmd
    - clt.qmd
    - propagation.qmd
    - fitting.qmd
    - hypotests.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



